In [2]:
from cms_top_20_001_Limits import getSMLO
import numpy as np
import pandas as pd

In [17]:
smLO = getSMLO()
smLO = smLO*0.2877
smLODF = pd.read_pickle('sm_lo.pcl')
binCols = [c for c in smLODF.columns if 'bin' in c and not 'Error' in c]
smLOmg = np.array([smLODF.iloc[0][c] for c in binCols])

In [18]:
print(sum(smLO))
print(sum(smLOmg))

162.06906858021057
152.2775072928196


In [19]:
smLO

array([3.34493116e+01, 5.09371553e+01, 3.15310506e+01, 1.83409803e+01,
       1.05228836e+01, 6.23953451e+00, 4.50878854e+00, 2.55260315e+00,
       2.00075466e+00, 9.36440697e-01, 5.83614218e-01, 2.42456781e-01,
       1.44890617e-01, 5.05658528e-02, 2.80381171e-02])

In [20]:
smLOmg

array([3.14087288e+01, 4.80535842e+01, 2.94725377e+01, 1.71137655e+01,
       9.99440555e+00, 5.81520797e+00, 4.20782691e+00, 2.37839729e+00,
       1.90019387e+00, 8.84111269e-01, 5.57791610e-01, 2.52006922e-01,
       1.48353646e-01, 5.55468631e-02, 3.50492873e-02])

In [21]:
smLOmg/smLO

array([0.93899477, 0.94338963, 0.93471474, 0.93308892, 0.94977821,
       0.93199388, 0.93325   , 0.93175365, 0.94973857, 0.9441188 ,
       0.95575398, 1.03938904, 1.02390099, 1.09850542, 1.25005853])