In [1]:
from cms_top_20_001_Limits import getSMLO, read_CMSdata, getKfactor,bin_widths
import numpy as np
import pandas as pd

In [2]:
data, smNLO, cov = read_CMSdata()
smLO = getSMLO()
k = getKfactor(smNLO,smLO)
smLODF = pd.read_pickle('./sm/sm_tt_lo_cms_top_20_001.pcl')
binCols = [c for c in smLODF.columns if 'bin' in c and not 'Error' in c]
smLOmg = np.array([smLODF.iloc[0][c] for c in binCols])

In [3]:
print(smNLO/(smLO*k))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
print((smLO*k/bin_widths)/data)

[0.95081967 1.00983607 1.         1.00655738 1.00655738 0.99672131
 1.03606557 0.99016393 1.07213115 1.00655738 1.11803279 1.00655738
 0.98032787 1.24262295 1.19016393]


In [5]:
print(smNLO/(smLO*k))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
print((smNLO/bin_widths)/data)

[0.95081967 1.00983607 1.         1.00655738 1.00655738 0.99672131
 1.03606557 0.99016393 1.07213115 1.00655738 1.11803279 1.00655738
 0.98032787 1.24262295 1.19016393]


In [7]:
k

array([1.59918665, 1.502596  , 1.49597211, 1.49786422, 1.49527662,
       1.50913797, 1.54316104, 1.51628949, 1.52891741, 1.53115308,
       1.51577723, 1.4117779 , 1.32329361, 1.3359564 , 1.27119371])

In [8]:
sum(smNLO)/0.2877,sum(smLOmg)/0.2877

(790.849106275321, 519.6665993356364)

In [9]:
832./790.

1.0531645569620254